
%! reago(+Nomo,+Produkto,+Substrato,+Enzimo,+Koenzimoj,+ReagTipo)

reago(cc_1,[citrato],
    okzalacetato,
    citrat_sintazo,
    [acetil_CoA,'H2O'],
    kondensado).
reago(cc_2a,[cis_akonitato,'H2O'],
    citrato,
    akonitazo,
    [],
    malhidratigo
    ).
reago(cc_2b,[izocitrato],
    cis_akonitato,
    akonitazo,
    ['H2O'],
    hidratigo).
reago(cc3a,[okzalsukcinato,'NADH'],
    izocitrato,
    izocitrat_dehidrogenazo,
    ['NAD+'],
    oksidigo
    ).
reago(cc_3b,[alfo_ketoglutarato,'CO2'],
    okzalsukcinato,
    izocitrat_dehidrogenazo,
    ['H+'],
    senkarboksiligo).
reago(cc_4,[sukcinilo_CoA,'NADH','CO2'],
    alfo_ketoglutarato,
    alfo_ketoglutarat_dehidrogenazo_komplekso,
    ['NAD+','CoA-SH'],
    senkarboksiligo
    ).
reago(cc_5,[sukcinato,'GTP','CoA-SH'],
    sukcinilo_CoA,
    sukcinil_CoA_sintetazo,
    ['GDP',fosfato],
    oksidiga_senkarboksiligo).
reago(cc_6,[fumarato,'FADH2'],
    sukcinato,
    sukcinat_dehidrogenazo,
    ['FAD'],
    fosfattransigo).
reago(cc_7,[l_malato],
    fumarato,
    fumarazo,
    ['H2O'],
    hidratigo).
reago(cc_8,[okzalacetato,'NADH'],
    l_malato,
    malatdehidrogenazo,
    ['NAD+'],
    oksidigo).

